import 'package:sdui_core/src/catalog/field_kind.dart';
import 'package:sdui_core/src/catalog/prop_field.dart';
import 'package:sdui_core/src/catalog/prop_option.dart';
import 'package:sdui_core/src/catalog/widget_descriptor.dart';
import 'package:sdui_core/src/model/sdui_node.dart';

const List<PropField> _flexFields = [
  PropField(
    key: 'mainAxisAlignment',
    kind: FieldKind.enumeration,
    label: 'Alinhamento principal',
    group: FieldGroups.layout,
    options: [
      PropOption('start', label: 'Início', iconName: 'flexStart'),
      PropOption('center', label: 'Centro', iconName: 'flexCenter'),
      PropOption('end', label: 'Fim', iconName: 'flexEnd'),
      PropOption(
        'spaceBetween',
        label: 'Espaço entre',
        iconName: 'flexSpaceBetween',
      ),
      PropOption(
        'spaceAround',
        label: 'Espaço ao redor',
        iconName: 'flexSpaceAround',
      ),
      PropOption(
        'spaceEvenly',
        label: 'Espaço uniforme',
        iconName: 'flexSpaceEvenly',
      ),
    ],
    defaultValue: 'start',
  ),
  PropField(
    key: 'crossAxisAlignment',
    kind: FieldKind.enumeration,
    label: 'Alinhamento cruzado',
    group: FieldGroups.layout,
    options: [
      PropOption('start', label: 'Início', iconName: 'crossStart'),
      PropOption('center', label: 'Centro', iconName: 'crossCenter'),
      PropOption('end', label: 'Fim', iconName: 'crossEnd'),
      PropOption('stretch', label: 'Esticar', iconName: 'crossStretch'),
    ],
    defaultValue: 'center',
  ),
  PropField(
    key: 'mainAxisSize',
    kind: FieldKind.enumeration,
    label: 'Tamanho do eixo',
    group: FieldGroups.layout,
    options: [
      PropOption('max', label: 'Expandir', iconName: 'sizeMax'),
      PropOption('min', label: 'Encolher', iconName: 'sizeMin'),
    ],
    defaultValue: 'max',
  ),
  PropField(
    key: 'spacing',
    kind: FieldKind.doubleNum,
    label: 'Espaço entre filhos',
    group: FieldGroups.spacing,
    min: 0,
    max: 64,
    defaultValue: 0.0,
  ),
];

final Map<String, WidgetDescriptor> widgetCatalog = Map.unmodifiable({
  'container': const WidgetDescriptor(
    type: 'container',
    label: 'Container',
    iconName: 'container',
    category: WidgetCategories.layout,
    slot: SlotKind.single,
    fields: [
      PropField(
        key: 'width',
        kind: FieldKind.doubleNum,
        label: 'Largura',
        group: FieldGroups.size,
        min: 0,
      ),
      PropField(
        key: 'height',
        kind: FieldKind.doubleNum,
        label: 'Altura',
        group: FieldGroups.size,
        min: 0,
      ),
      PropField(
        key: 'padding',
        kind: FieldKind.edgeInsets,
        label: 'Padding',
        group: FieldGroups.spacing,
      ),
      PropField(
        key: 'margin',
        kind: FieldKind.edgeInsets,
        label: 'Margin',
        group: FieldGroups.spacing,
      ),
      PropField(
        key: 'alignment',
        kind: FieldKind.alignment,
        label: 'Alinhamento do filho',
        group: FieldGroups.layout,
      ),
      PropField(
        key: 'color',
        kind: FieldKind.color,
        label: 'Cor de fundo',
        group: FieldGroups.style,
      ),
      PropField(
        key: 'borderRadius',
        kind: FieldKind.doubleNum,
        label: 'Raio da borda',
        group: FieldGroups.style,
        min: 0,
        max: 64,
      ),
      PropField(
        key: 'borderColor',
        kind: FieldKind.color,
        label: 'Cor da borda',
        group: FieldGroups.style,
      ),
      PropField(
        key: 'borderWidth',
        kind: FieldKind.doubleNum,
        label: 'Espessura da borda',
        group: FieldGroups.style,
        min: 0,
        max: 16,
      ),
    ],
  ),
  'column': const WidgetDescriptor(
    type: 'column',
    label: 'Column',
    iconName: 'column',
    category: WidgetCategories.layout,
    slot: SlotKind.multi,
    fields: _flexFields,
  ),
  'row': const WidgetDescriptor(
    type: 'row',
    label: 'Row',
    iconName: 'row',
    category: WidgetCategories.layout,
    slot: SlotKind.multi,
    fields: _flexFields,
  ),
  'stack': const WidgetDescriptor(
    type: 'stack',
    label: 'Stack',
    iconName: 'stack',
    category: WidgetCategories.layout,
    slot: SlotKind.multi,
    fields: [
      PropField(
        key: 'alignment',
        kind: FieldKind.alignment,
        label: 'Alinhamento',
        group: FieldGroups.layout,
      ),
      PropField(
        key: 'fit',
        kind: FieldKind.enumeration,
        label: 'Ajuste',
        group: FieldGroups.layout,
        options: [
          PropOption('loose', label: 'Livre'),
          PropOption('expand', label: 'Expandir'),
          PropOption('passthrough', label: 'Repassar'),
        ],
        defaultValue: 'loose',
      ),
    ],
  ),
  'text': const WidgetDescriptor(
    type: 'text',
    label: 'Text',
    iconName: 'text',
    category: WidgetCategories.content,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'data',
        kind: FieldKind.string,
        label: 'Texto',
        group: FieldGroups.content,
        defaultValue: 'Texto',
        isRequired: true,
      ),
      PropField(
        key: 'fontSize',
        kind: FieldKind.doubleNum,
        label: 'Tamanho da fonte',
        group: FieldGroups.style,
        min: 8,
        max: 96,
        defaultValue: 14.0,
      ),
      PropField(
        key: 'fontWeight',
        kind: FieldKind.enumeration,
        label: 'Peso da fonte',
        group: FieldGroups.style,
        options: [
          PropOption('w100', label: 'Thin 100'),
          PropOption('w200', label: 'ExtraLight 200'),
          PropOption('w300', label: 'Light 300'),
          PropOption('w400', label: 'Regular 400'),
          PropOption('w500', label: 'Medium 500'),
          PropOption('w600', label: 'SemiBold 600'),
          PropOption('w700', label: 'Bold 700'),
          PropOption('w800', label: 'ExtraBold 800'),
          PropOption('w900', label: 'Black 900'),
        ],
        defaultValue: 'w400',
      ),
      PropField(
        key: 'color',
        kind: FieldKind.color,
        label: 'Cor',
        group: FieldGroups.style,
      ),
      PropField(
        key: 'textAlign',
        kind: FieldKind.enumeration,
        label: 'Alinhamento do texto',
        group: FieldGroups.content,
        options: [
          PropOption('start', label: 'Início', iconName: 'textAlignStart'),
          PropOption('center', label: 'Centro', iconName: 'textAlignCenter'),
          PropOption('end', label: 'Fim', iconName: 'textAlignEnd'),
          PropOption(
            'justify',
            label: 'Justificado',
            iconName: 'textAlignJustify',
          ),
          PropOption('left', label: 'Esquerda', iconName: 'textAlignLeft'),
          PropOption('right', label: 'Direita', iconName: 'textAlignRight'),
        ],
        defaultValue: 'start',
      ),
      PropField(
        key: 'maxLines',
        kind: FieldKind.intNum,
        label: 'Máximo de linhas',
        group: FieldGroups.content,
        min: 1,
        max: 20,
      ),
      PropField(
        key: 'overflow',
        kind: FieldKind.enumeration,
        label: 'Overflow',
        group: FieldGroups.content,
        options: [
          PropOption('clip', label: 'Cortar'),
          PropOption('fade', label: 'Esmaecer'),
          PropOption('ellipsis', label: 'Reticências'),
          PropOption('visible', label: 'Visível'),
        ],
        defaultValue: 'clip',
      ),
    ],
  ),
  'image': const WidgetDescriptor(
    type: 'image',
    label: 'Image',
    iconName: 'image',
    category: WidgetCategories.content,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'src',
        kind: FieldKind.string,
        label: 'URL da imagem',
        group: FieldGroups.content,
        isRequired: true,
      ),
      PropField(
        key: 'width',
        kind: FieldKind.doubleNum,
        label: 'Largura',
        group: FieldGroups.size,
        min: 0,
      ),
      PropField(
        key: 'height',
        kind: FieldKind.doubleNum,
        label: 'Altura',
        group: FieldGroups.size,
        min: 0,
      ),
      PropField(
        key: 'fit',
        kind: FieldKind.enumeration,
        label: 'Ajuste',
        group: FieldGroups.content,
        options: [
          PropOption('fill', label: 'Preencher'),
          PropOption('contain', label: 'Conter'),
          PropOption('cover', label: 'Cobrir'),
          PropOption('fitWidth', label: 'Ajustar largura'),
          PropOption('fitHeight', label: 'Ajustar altura'),
          PropOption('none', label: 'Nenhum'),
          PropOption('scaleDown', label: 'Reduzir'),
        ],
        defaultValue: 'contain',
      ),
    ],
  ),
  'icon': const WidgetDescriptor(
    type: 'icon',
    label: 'Icon',
    iconName: 'icon',
    category: WidgetCategories.content,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'icon',
        kind: FieldKind.iconName,
        label: 'Ícone',
        group: FieldGroups.content,
        defaultValue: 'star',
        isRequired: true,
      ),
      PropField(
        key: 'size',
        kind: FieldKind.doubleNum,
        label: 'Tamanho',
        group: FieldGroups.style,
        min: 8,
        max: 96,
        defaultValue: 24.0,
      ),
      PropField(
        key: 'color',
        kind: FieldKind.color,
        label: 'Cor',
        group: FieldGroups.style,
      ),
    ],
  ),
  'button': const WidgetDescriptor(
    type: 'button',
    label: 'Button',
    iconName: 'button',
    category: WidgetCategories.interaction,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'label',
        kind: FieldKind.string,
        label: 'Rótulo',
        group: FieldGroups.content,
        defaultValue: 'Botão',
        isRequired: true,
      ),
      PropField(
        key: 'variant',
        kind: FieldKind.enumeration,
        label: 'Variante',
        group: FieldGroups.style,
        options: [
          PropOption('elevated', label: 'Elevado'),
          PropOption('filled', label: 'Preenchido'),
          PropOption('outlined', label: 'Contornado'),
          PropOption('text', label: 'Texto'),
        ],
        defaultValue: 'elevated',
      ),
      PropField(
        key: 'backgroundColor',
        kind: FieldKind.color,
        label: 'Cor de fundo',
        group: FieldGroups.style,
      ),
      PropField(
        key: 'foregroundColor',
        kind: FieldKind.color,
        label: 'Cor do conteúdo',
        group: FieldGroups.style,
      ),
      PropField(
        key: 'borderRadius',
        kind: FieldKind.doubleNum,
        label: 'Raio da borda',
        group: FieldGroups.style,
        min: 0,
        max: 64,
      ),
      PropField(
        key: 'fontSize',
        kind: FieldKind.doubleNum,
        label: 'Tamanho da fonte',
        group: FieldGroups.style,
        min: 8,
        max: 96,
      ),
      PropField(
        key: 'enabled',
        kind: FieldKind.boolean,
        label: 'Habilitado',
        group: FieldGroups.content,
        defaultValue: true,
      ),
    ],
  ),
  'textField': const WidgetDescriptor(
    type: 'textField',
    label: 'TextField',
    iconName: 'textField',
    category: WidgetCategories.interaction,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'label',
        kind: FieldKind.string,
        label: 'Rótulo',
        group: FieldGroups.content,
        defaultValue: 'Rótulo',
      ),
      PropField(
        key: 'hint',
        kind: FieldKind.string,
        label: 'Placeholder',
        group: FieldGroups.content,
        defaultValue: 'Digite aqui',
      ),
      PropField(
        key: 'value',
        kind: FieldKind.string,
        label: 'Texto inicial',
        group: FieldGroups.content,
      ),
      PropField(
        key: 'helperText',
        kind: FieldKind.string,
        label: 'Texto de apoio',
        group: FieldGroups.content,
      ),
      PropField(
        key: 'obscureText',
        kind: FieldKind.boolean,
        label: 'Ocultar texto',
        group: FieldGroups.content,
        defaultValue: false,
      ),
      PropField(
        key: 'enabled',
        kind: FieldKind.boolean,
        label: 'Habilitado',
        group: FieldGroups.content,
        defaultValue: true,
      ),
      PropField(
        key: 'keyboardType',
        kind: FieldKind.enumeration,
        label: 'Tipo de teclado',
        group: FieldGroups.content,
        options: [
          PropOption('text', label: 'Texto'),
          PropOption('number', label: 'Número'),
          PropOption('email', label: 'E-mail'),
          PropOption('phone', label: 'Telefone'),
          PropOption('url', label: 'URL'),
        ],
        defaultValue: 'text',
      ),
      PropField(
        key: 'maxLength',
        kind: FieldKind.intNum,
        label: 'Máximo de caracteres',
        group: FieldGroups.content,
        min: 1,
        max: 500,
      ),
      PropField(
        key: 'prefixIcon',
        kind: FieldKind.iconName,
        label: 'Ícone à esquerda',
        group: FieldGroups.style,
      ),
      PropField(
        key: 'borderStyle',
        kind: FieldKind.enumeration,
        label: 'Estilo da borda',
        group: FieldGroups.style,
        options: [
          PropOption('outline', label: 'Contorno', iconName: 'borderOutline'),
          PropOption(
            'underline',
            label: 'Sublinhado',
            iconName: 'borderUnderline',
          ),
          PropOption('filled', label: 'Preenchido', iconName: 'borderFilled'),
        ],
        defaultValue: 'outline',
      ),
    ],
  ),
  'switch': const WidgetDescriptor(
    type: 'switch',
    label: 'Switch',
    iconName: 'switch',
    category: WidgetCategories.interaction,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'value',
        kind: FieldKind.boolean,
        label: 'Ligado',
        group: FieldGroups.content,
        defaultValue: false,
      ),
      PropField(
        key: 'label',
        kind: FieldKind.string,
        label: 'Rótulo',
        group: FieldGroups.content,
      ),
      PropField(
        key: 'enabled',
        kind: FieldKind.boolean,
        label: 'Habilitado',
        group: FieldGroups.content,
        defaultValue: true,
      ),
      PropField(
        key: 'activeColor',
        kind: FieldKind.color,
        label: 'Cor quando ligado',
        group: FieldGroups.style,
      ),
    ],
  ),
  'checkbox': const WidgetDescriptor(
    type: 'checkbox',
    label: 'Checkbox',
    iconName: 'checkbox',
    category: WidgetCategories.interaction,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'value',
        kind: FieldKind.boolean,
        label: 'Marcado',
        group: FieldGroups.content,
        defaultValue: false,
      ),
      PropField(
        key: 'label',
        kind: FieldKind.string,
        label: 'Rótulo',
        group: FieldGroups.content,
      ),
      PropField(
        key: 'enabled',
        kind: FieldKind.boolean,
        label: 'Habilitado',
        group: FieldGroups.content,
        defaultValue: true,
      ),
      PropField(
        key: 'activeColor',
        kind: FieldKind.color,
        label: 'Cor quando marcado',
        group: FieldGroups.style,
      ),
    ],
  ),
  'card': const WidgetDescriptor(
    type: 'card',
    label: 'Card',
    iconName: 'card',
    category: WidgetCategories.layout,
    slot: SlotKind.single,
    fields: [
      PropField(
        key: 'color',
        kind: FieldKind.color,
        label: 'Cor',
        group: FieldGroups.style,
      ),
      PropField(
        key: 'elevation',
        kind: FieldKind.doubleNum,
        label: 'Elevação',
        group: FieldGroups.style,
        min: 0,
        max: 24,
      ),
      PropField(
        key: 'borderRadius',
        kind: FieldKind.doubleNum,
        label: 'Raio da borda',
        group: FieldGroups.style,
        min: 0,
        max: 64,
      ),
      PropField(
        key: 'margin',
        kind: FieldKind.edgeInsets,
        label: 'Margin',
        group: FieldGroups.spacing,
      ),
    ],
  ),
  'divider': const WidgetDescriptor(
    type: 'divider',
    label: 'Divider',
    iconName: 'divider',
    category: WidgetCategories.layout,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'thickness',
        kind: FieldKind.doubleNum,
        label: 'Espessura',
        group: FieldGroups.style,
        min: 0,
        max: 16,
      ),
      PropField(
        key: 'color',
        kind: FieldKind.color,
        label: 'Cor',
        group: FieldGroups.style,
      ),
      PropField(
        key: 'indent',
        kind: FieldKind.doubleNum,
        label: 'Recuo inicial',
        group: FieldGroups.spacing,
        min: 0,
        max: 64,
      ),
      PropField(
        key: 'endIndent',
        kind: FieldKind.doubleNum,
        label: 'Recuo final',
        group: FieldGroups.spacing,
        min: 0,
        max: 64,
      ),
    ],
  ),
  'sizedBox': const WidgetDescriptor(
    type: 'sizedBox',
    label: 'SizedBox',
    iconName: 'sizedBox',
    category: WidgetCategories.layout,
    slot: SlotKind.single,
    fields: [
      PropField(
        key: 'width',
        kind: FieldKind.doubleNum,
        label: 'Largura',
        group: FieldGroups.size,
        min: 0,
      ),
      PropField(
        key: 'height',
        kind: FieldKind.doubleNum,
        label: 'Altura',
        group: FieldGroups.size,
        min: 0,
      ),
    ],
  ),
  'padding': const WidgetDescriptor(
    type: 'padding',
    label: 'Padding',
    iconName: 'padding',
    category: WidgetCategories.layout,
    slot: SlotKind.single,
    fields: [
      PropField(
        key: 'padding',
        kind: FieldKind.edgeInsets,
        label: 'Padding',
        group: FieldGroups.spacing,
        defaultValue: {'all': 8.0},
        isRequired: true,
      ),
    ],
  ),
  'center': const WidgetDescriptor(
    type: 'center',
    label: 'Center',
    iconName: 'center',
    category: WidgetCategories.layout,
    slot: SlotKind.single,
    fields: [
      PropField(
        key: 'widthFactor',
        kind: FieldKind.doubleNum,
        label: 'Fator de largura',
        group: FieldGroups.size,
        min: 0,
        max: 5,
        step: 0.1,
      ),
      PropField(
        key: 'heightFactor',
        kind: FieldKind.doubleNum,
        label: 'Fator de altura',
        group: FieldGroups.size,
        min: 0,
        max: 5,
        step: 0.1,
      ),
    ],
  ),
  'spacer': const WidgetDescriptor(
    type: 'spacer',
    label: 'Spacer',
    iconName: 'spacer',
    category: WidgetCategories.layout,
    slot: SlotKind.none,
    fields: [
      PropField(
        key: 'flex',
        kind: FieldKind.intNum,
        label: 'Flex',
        group: FieldGroups.layout,
        min: 1,
        max: 12,
        defaultValue: 1,
      ),
    ],
  ),
});

WidgetDescriptor? descriptorFor(String type) => widgetCatalog[type];

SduiNode defaultNode(String type, {required String id}) {
  final descriptor = widgetCatalog[type];
  if (descriptor == null) {
    throw ArgumentError.value(type, 'type', 'tipo fora do catálogo');
  }
  final defaults = <String, dynamic>{
    for (final field in descriptor.fields)
      if (field.defaultValue != null) field.key: field.defaultValue,
  };
  return SduiNode(id: id, type: type, properties: defaults);
}
